// PLACEHOLDER — all data below is hardcoded for the Phase 2 static prototype
import type { Combatant, CombatLogEntry } from '../../fileSystem/schema';

export const FAKE_CURRENT_TURN_INDEX = 1;
export const FAKE_ROUND = 2;
export const FAKE_RECOMMENDED_ACTION_IDS = ['lich-touch', 'lich-disrupt'];

export const FAKE_COMBATANTS: Combatant[] = [
  {
    id: 'aldric',
    name: 'Aldric Voss',
    type: 'player_character',
    ac: 18,
    max_hp: 52,
    current_hp: 38,
    temp_hp: 0,
    speed: 30,
    initiative: 20,
    initiative_modifier: 2,
    conditions: [],
    actions: [
      {
        id: 'aldric-longsword',
        name: 'Longsword',
        action_category: 'action',
        attack_bonus: 6,
        damage: '1d8+4',
        damage_type: 'slashing',
        range_hint: 'melee',
        available: true,
      },
      {
        id: 'aldric-surge',
        name: 'Action Surge',
        action_category: 'action',
        range_hint: 'self',
        available: false,
        uses_max: 1,
        uses_remaining: 0,
      },
    ],
    bonus_actions: [
      {
        id: 'aldric-second-wind',
        name: 'Second Wind',
        action_category: 'bonus_action',
        range_hint: 'self',
        available: true,
        uses_max: 1,
        uses_remaining: 1,
      },
    ],
    reactions: [],
    spell_slots: {},
    resistances: [],
    immunities: [],
    vulnerabilities: [],
    legendary_actions_max: 0,
    legendary_actions_remaining: 0,
    archetype: null,
    notes: '',
  },
  {
    id: 'lich',
    name: 'Lich King',
    type: 'enemy_npc',
    ac: 17,
    max_hp: 135,
    current_hp: 97,
    temp_hp: 0,
    speed: 30,
    initiative: 18,
    initiative_modifier: 3,
    conditions: [{ condition: 'frightened', source: 'Turn Undead' }],
    actions: [
      {
        id: 'lich-touch',
        name: 'Paralyzing Touch',
        action_category: 'action',
        attack_bonus: 7,
        damage: '3d6',
        damage_type: 'cold',
        range_hint: 'melee',
        save_dc: 18,
        save_ability: 'Con',
        available: true,
      },
      {
        id: 'lich-disrupt',
        name: 'Disrupt Life',
        action_category: 'action',
        range_hint: 'area',
        save_dc: 18,
        save_ability: 'Con',
        damage: '8d6',
        damage_type: 'necrotic',
        recharge: '5-6',
        available: true,
      },
    ],
    bonus_actions: [],
    reactions: [],
    legendary_actions: [
      {
        id: 'lich-cantrip',
        name: 'Cantrip',
        action_category: 'legendary',
        range_hint: 'ranged_60',
        available: true,
      },
      {
        id: 'lich-paralyze',
        name: 'Paralyzing Touch (Legendary)',
        action_category: 'legendary',
        range_hint: 'melee',
        available: false,
        uses_max: 1,
        uses_remaining: 0,
      },
    ],
    spell_slots: {
      1: { max: 4, remaining: 2 },
      2: { max: 3, remaining: 3 },
      3: { max: 3, remaining: 1 },
      4: { max: 3, remaining: 3 },
      5: { max: 2, remaining: 2 },
    },
    resistances: [],
    immunities: ['poison'],
    vulnerabilities: [],
    legendary_actions_max: 3,
    legendary_actions_remaining: 2,
    archetype: 'boss',
    notes: '',
  },
  {
    id: 'mira',
    name: 'Mira Dawnwhisper',
    type: 'player_character',
    ac: 16,
    max_hp: 44,
    current_hp: 44,
    temp_hp: 5,
    speed: 30,
    initiative: 15,
    initiative_modifier: 1,
    conditions: [],
    actions: [
      {
        id: 'mira-mace',
        name: 'Mace',
        action_category: 'action',
        attack_bonus: 4,
        damage: '1d6+2',
        damage_type: 'bludgeoning',
        range_hint: 'melee',
        available: true,
      },
      {
        id: 'mira-sacred-flame',
        name: 'Sacred Flame',
        action_category: 'action',
        range_hint: 'ranged_60',
        save_dc: 14,
        save_ability: 'Dex',
        damage: '2d8',
        damage_type: 'radiant',
        available: true,
      },
      {
        id: 'mira-spirit-guardians',
        name: 'Spirit Guardians',
        action_category: 'action',
        range_hint: 'self',
        damage: '3d8',
        damage_type: 'radiant',
        spell_slot_level: 3,
        available: false,
      },
    ],
    bonus_actions: [
      {
        id: 'mira-healing-word',
        name: 'Healing Word',
        action_category: 'bonus_action',
        range_hint: 'ranged_60',
        damage: '1d4+4',
        spell_slot_level: 1,
        available: true,
      },
    ],
    reactions: [
      {
        id: 'mira-shield-of-faith',
        name: 'Shield of Faith',
        action_category: 'reaction',
        range_hint: 'touch',
        available: true,
      },
    ],
    spell_slots: {
      1: { max: 4, remaining: 3 },
      2: { max: 3, remaining: 2 },
      3: { max: 3, remaining: 2 },
    },
    resistances: [],
    immunities: [],
    vulnerabilities: [],
    legendary_actions_max: 0,
    legendary_actions_remaining: 0,
    archetype: null,
    notes: '',
  },
  {
    id: 'goblin',
    name: 'Goblin Archer',
    type: 'enemy_npc',
    ac: 13,
    max_hp: 7,
    current_hp: 3,
    temp_hp: 0,
    speed: 30,
    initiative: 12,
    initiative_modifier: 2,
    conditions: [{ condition: 'prone' }],
    actions: [
      {
        id: 'goblin-shortbow',
        name: 'Shortbow',
        action_category: 'action',
        attack_bonus: 4,
        damage: '1d6+2',
        damage_type: 'piercing',
        range_hint: 'ranged_60',
        available: true,
      },
      {
        id: 'goblin-scimitar',
        name: 'Scimitar',
        action_category: 'action',
        attack_bonus: 4,
        damage: '1d6+2',
        damage_type: 'slashing',
        range_hint: 'melee',
        available: true,
      },
    ],
    bonus_actions: [
      {
        id: 'goblin-nimble',
        name: 'Nimble Escape',
        action_category: 'bonus_action',
        range_hint: 'self',
        available: true,
      },
    ],
    reactions: [],
    spell_slots: {},
    resistances: [],
    immunities: [],
    vulnerabilities: [],
    legendary_actions_max: 0,
    legendary_actions_remaining: 0,
    archetype: 'skirmisher',
    notes: '',
  },
  {
    id: 'theron',
    name: 'Theron Brightblade',
    type: 'allied_npc',
    ac: 14,
    max_hp: 28,
    current_hp: 28,
    temp_hp: 0,
    speed: 30,
    initiative: 10,
    initiative_modifier: 0,
    conditions: [],
    actions: [
      {
        id: 'theron-shortsword',
        name: 'Shortsword',
        action_category: 'action',
        attack_bonus: 3,
        damage: '1d6+1',
        damage_type: 'piercing',
        range_hint: 'melee',
        available: true,
      },
    ],
    bonus_actions: [
      {
        id: 'theron-healing-word',
        name: 'Healing Word',
        action_category: 'bonus_action',
        range_hint: 'ranged_60',
        damage: '1d4+3',
        spell_slot_level: 1,
        available: true,
      },
    ],
    reactions: [],
    spell_slots: {
      1: { max: 2, remaining: 1 },
    },
    resistances: [],
    immunities: [],
    vulnerabilities: [],
    legendary_actions_max: 0,
    legendary_actions_remaining: 0,
    archetype: 'support',
    notes: '',
  },
  {
    id: 'skeleton',
    name: 'Skeleton Warrior',
    type: 'enemy_npc',
    ac: 13,
    max_hp: 13,
    current_hp: 0,
    temp_hp: 0,
    speed: 30,
    initiative: 6,
    initiative_modifier: -1,
    conditions: [{ condition: 'unconscious' }],
    actions: [
      {
        id: 'skel-shortsword',
        name: 'Shortsword',
        action_category: 'action',
        attack_bonus: 4,
        damage: '1d6+2',
        damage_type: 'piercing',
        range_hint: 'melee',
        available: false,
      },
    ],
    bonus_actions: [],
    reactions: [],
    spell_slots: {},
    resistances: [],
    immunities: ['poison'],
    vulnerabilities: [],
    legendary_actions_max: 0,
    legendary_actions_remaining: 0,
    archetype: 'brute',
    notes: '',
  },
];

export const FAKE_LOG_ENTRIES: CombatLogEntry[] = [
  {
    id: 'log-1',
    round: 1,
    combatant_id: 'aldric',
    combatant_name: 'Aldric Voss',
    action_id: 'aldric-longsword',
    action_name: 'Longsword',
    action_category: 'action',
    target_ids: ['lich'],
    target_names: ['Lich King'],
    roll_to_hit: 19,
    hit: true,
    damage_amount: 11,
    damage_type: 'slashing',
    timestamp: '2024-01-01T00:00:01Z',
  },
  {
    id: 'log-2',
    round: 1,
    combatant_id: 'lich',
    combatant_name: 'Lich King',
    action_id: 'lich-disrupt',
    action_name: 'Disrupt Life',
    action_category: 'action',
    target_ids: ['aldric', 'mira', 'theron'],
    target_names: ['Aldric Voss', 'Mira Dawnwhisper', 'Theron Brightblade'],
    damage_amount: 28,
    damage_type: 'necrotic',
    timestamp: '2024-01-01T00:00:02Z',
  },
  {
    id: 'log-3',
    round: 1,
    combatant_id: 'mira',
    combatant_name: 'Mira Dawnwhisper',
    action_id: 'mira-healing-word',
    action_name: 'Healing Word',
    action_category: 'bonus_action',
    target_ids: ['aldric'],
    target_names: ['Aldric Voss'],
    damage_amount: 9,
    timestamp: '2024-01-01T00:00:03Z',
  },
  {
    id: 'log-4',
    round: 2,
    combatant_id: 'aldric',
    combatant_name: 'Aldric Voss',
    action_id: 'aldric-longsword',
    action_name: 'Longsword',
    action_category: 'action',
    target_ids: ['lich'],
    target_names: ['Lich King'],
    roll_to_hit: 22,
    hit: true,
    damage_amount: 14,
    damage_type: 'slashing',
    timestamp: '2024-01-01T00:00:04Z',
  },
  {
    id: 'log-5',
    round: 2,
    combatant_id: 'lich',
    combatant_name: 'Lich King',
    action_id: 'lich-touch',
    action_name: 'Paralyzing Touch',
    action_category: 'action',
    target_ids: ['aldric'],
    target_names: ['Aldric Voss'],
    roll_to_hit: 15,
    hit: true,
    damage_amount: 9,
    damage_type: 'cold',
    conditions_applied: ['paralyzed'],
    timestamp: '2024-01-01T00:00:05Z',
  },
];
